#
# Makefile to build a Windows Version of LIBNODAVE using MSVC++ from Microsoft.
#
# type 'make' to build libnodave.dll and some statically linked test programs.
# type 'make dynamic' to make libnodave.dll and some dynamically linked test programs.
#
# The directory where the tools are:
#
VCPATH=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC
SDKPATH=C:\Program Files (x86)\Microsoft SDKs\Windows\v7.1A\


CC="$(VCPATH)\bin\amd64\cl"
LL="$(VCPATH)\bin\amd64\link"

CFLAGS= -I"$(VCPATH)\include" -I"$(SDKPATH)\include" -c -DBCCWIN -DDAVE_LITTLE_ENDIAN -TC
LFLAGS= /LIBPATH:"$(VCPATH)"\lib\x64,"$(SDKPATH)"\lib\x64
LLFLAGS = /LIBPATH:"$(VCPATH)\lib\x64" /DEF:libnodave.DEF /MACHINE:X64

PROGRAMS=testISO_TCP.exe
# PROGRAMS=testMPI.exe testPPI.exe testAS511.exe\
# testPPI_IBH.exe testPPI_IBHload.exe testPPIload.exe \
# testMPIload.exe testISO_TCP.exe testISO_TCPload.exe testIBH.exe testMPI_IBHload.exe \
# testNLpro.exe testS7online.exe

LIBRARIES=libnodave_jfkmod64.dll

all: $(PROGRAMS) $(LIBRARIES)

dynamic: $(DYNAMIC_PROGRAMS)

testISO_TCP.exe: nodave.obj openSocketw.obj testISO_TCP.obj
	$(LL) $(LFLAGS) testISO_TCP.obj openSocketw.obj nodave.obj "$(SDKPATH)"\lib\x64\ws2_32.lib /OUT:testISO_TCP.exe
libnodave_jfkmod64.dll: nodave.obj setportw.obj openSocketw.obj openS7online.obj 
	$(LL) $(LLFLAGS) /DLL nodave.obj setportw.obj openSocketw.obj openS7online.obj "$(SDKPATH)"\lib\x64\ws2_32.lib /OUT:libnodave_jfkmod64.dll
		
#
# delete all but the sources:
#
clean: 	
	del /f /q *.tds *.il? *.obj *.map *.lib *.dll *.exe *.exp *.o *.a
distclean: 	
	del /f /q *.tds *.il? *.obj *.map

nodave.obj: nodave.c nodave.h
	$(CC) $(CFLAGS) -DDOEXPORT nodave.c
setportw.obj: setportw.c
	$(CC) $(CFLAGS) -DDOEXPORT setportw.c
openSocketw.obj: openSocketw.c
	$(CC) $(CFLAGS) -DDOEXPORT openSocketw.c
openS7online.obj: openS7online.c openS7online.h 
	$(CC) $(CFLAGS) -DDOEXPORT openS7online.c
s7fake.obj: s7fake.c
	$(CC) $(CFLAGS) -DDOEXPORT s7fake.c
